---
- name: Install docker
  hosts: web
  gather_facts: false
  become: true
  
  tasks:
  - name: Install Docker
    apt:
      name: "docker-ce"
      force_apt_get: "yes"


  - name: Clone git
    git:
      repo: https://github.com/j0h3/cours_ynov.git

